### ISSUE TITLE
ドラッグ移動機能

### ISSUE THREAD

**Issue by Ryuyxx** [tapioca24/p5.capture#1]
## 概要
素晴らしいライブラリありがとうございます!!

固定でも良いのですが、このcontainerが**ドラッグ移動**出来たらより便利かなと思いました。

(forkし少し[実装](https://github.com/Ryuyxx/p5.capture/commit/3de6659d846f5441433bf8ac015e8d5d28e180ea)したのですが、自分の方法では[fiefoxに対応](https://bugzilla.mozilla.org/show_bug.cgi?id=505521)できなかったためissueに書かせていただきました:pray:)

## 例
<video src="https://user-images.githubusercontent.com/69892552/160174689-8d8e4f56-2297-4479-bf71-3310fe0db5ff.mp4" controls="controls" ></video>

以下の追加変更をここでは行っています。
- 背景色をグレーへ(背景白だと少し見づらく感じました)
- カーソルを`move`へ
- widthを`170px`へ固定

**Comment by tapioca24** [comment]
ご提案と実装に関する情報のご提供ありがとうございます。
めちゃめちゃ助かります🙏

確かにドラッグで移動できると便利そうです！
背景白だと見づらい件と合わせて対処したいと思います。

**Comment by tapioca24** [comment]
ドラッグ移動の追加と視認性の改善の対応を v1.1.0 としてリリースしました。

**Comment by tapioca24** [comment]
Thank you for suggesting this, @Ryuyxx :tada:
引き続き問題がある場合は再オープンしてください。
