### ISSUE TITLE
Running without interface

### ISSUE THREAD

**Issue by jcubic** [tapioca24/p5.capture#10]
It would be nice if you can use the library like a library without GUI.
I would like to have my own interface in my Code editor I don't want any extra interface.
Is something like this possible?

**Comment by tapioca24** [comment]
Hi, @jcubic.
You can hide the GUI using the `disableUi` option.
Here is an example:

```js
P5Capture.setDefaultOptions({
  disableUi: true,
});

function setup() {
  // do something...
}
```

**Comment by jcubic** [comment]
Thanks, it works great.
