### ISSUE TITLE
Screen is all black

### ISSUE THREAD

**Issue by jcubic** [tapioca24/p5.capture#11]
Here is an example animation that fails to record:

https://p5.javascript.org.pl/frantic-average?template=none

I was testing simpler code with the recorder and using script tag this way works fine. Except it fails to record any video, even though it's a simple rotating square.

This is a simplified version where I have a more complex function instead of a square. I've tried to reproduce the issue.

**Comment by jcubic** [comment]
I'm not sure what the problem is I was changing random things it something work sometimes doesn't.

I use Google Chrome on Fedora GNU/Linux.

**Comment by tapioca24** [comment]
Hi, @jcubic. Thank you for reporting this one!
I found that you are using the old p5.capture version in your example. Is this intentional?
Do you have the same problem when you try with the latest version?

**Comment by jcubic** [comment]
I used the version that was provided in your examples. I think that you should update your example and don't hardcode the version. You don't need to do that on jsDelivr.

Will try the latest version and let you know.

**Comment by jcubic** [comment]
I don't understand maybe you will be able to figure out if will have time.

I have my playground:
https://p5.javascript.org.pl/panicky-interest?template=none

Where I have a lot of comments (sorry they are in Polish) and redefined functions, the code is for my programming lessons where I have multiple functions as notes on how I should show the code step by step.

And the animation doesn't work, the video is all black. But when I copy-pasted only relevant code into that [previously linked sketch](https://p5.javascript.org.pl/frantic-average?template=none) it did not work.

**Comment by tapioca24** [comment]
> I think that you should update your example and don't hardcode the version. You don't need to do that on jsDelivr.

Oh, that was my mistake and I fixed my examples.
Thanks!

**Comment by tapioca24** [comment]
I confirmed that the video is all black.
I think the cause is that the background is transparent. On the web it looks normal because there is a white background behind the canvas. But if you don't specify a background, the canvas background seems to be transparent and is recorded as black pixels in the video.

Can you test if it works using the [`background` function](https://p5js.org/reference/#/p5/background)?

**Comment by jcubic** [comment]
There is white background, there is `rect(0, 0, width, height);` at the beginning. If you take a screenshot it's not transparent.


PS: You can edit the sketch, this is a prototype of the application that everyone can edit. I yet need to add some kind of user auth and permissions. I created a copy of my working sketch just in case if someone edit or delete the code.

**Comment by jcubic** [comment]
Yes, you're right. I was testing screenshots in the first frame only, if I start the animation, and grab the screen I got the transparent background.

Thanks for your help to debug this.

BTW: Your project is great, I love it.
