### ISSUE TITLE
Add support for instance mode

### ISSUE THREAD

**Issue by guilhermesilveira** [tapioca24/p5.capture#18]
In order to use p5 with several types of libraries, we need to restrict its usage to instance mode. For example, a react next project can not run p5 in global mode out of the box.

The most common situation for instance mode is to have one single instance per page. I have submitted a pull request #17  that adds support for instance mode, allowing the recording of a single canvas at a time.

In order to support multiple canvas recording at the same time, one needs to probably refactor the Singleton instance of p5.Capture, which I guess would be a different issue.

**Comment by tapioca24** [comment]
Released in v1.4.0. Thank you for all your contributions!

**Comment by AlexanderCleasby** [comment]
Is it possible to add some documentation on how to use this library in instance mode?
