### ISSUE TITLE
Package and npm

### ISSUE THREAD

**Issue by micvolo** [tapioca24/p5.capture#26]
Hi, first of all thanks for your work!

i'm trying to make your library works as an npm package in my Vite Project (Astro).
`npm i p5.capture` works well but it doesn't have a default export, so i have to import it in my project like that
``` js
    const sketch = (p5: P5) => {
        ... my setup and draw
    });
    new P5(sketch, container);

   // import your library
    await import('p5.capture')
```
 but i get the error:
 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/33074676/231182696-cd37bf9a-bcc8-4890-b150-042e0e45fac4.png">

I've read that your library is limited only to one p5.js instance mode, and that's what i have
I also tried to import it with the cdn with the same result.

Is there a way to make this import works?

Thanks for your time!!

**Comment by tapioca24** [comment]
Hi, @micvolo. Thank you for reporting this one!

Sorry about that! Just to let you know, p5.capture doesn't currently support use with module bundlers. I'll try to improve that in the future, but for now, please keep that in mind. Thanks for your help, and please let me know if you have any other questions or issues!
