### ISSUE TITLE
[feature request] segmented capture for large frames and long animations

### ISSUE THREAD

**Issue by SableRaf** [tapioca24/p5.capture#6]
When capturing many large frames with p5.capture, the browser can crash or the encoding step can take forever

I made this for my own purpose. It halts the sketch and saves the frames in batches:

https://editor.p5js.org/SableRaf/sketches/KuLI1oVPT

However it is a quick and dirty workaround and it would be amazing to have a solution built-in 😌

**Comment by tapioca24** [comment]
Hi, @SableRaf. Thank you for your request!

It sounds good.
I will work on it and update this issue to let you know :)

**Comment by tapioca24** [comment]
Hi, @SableRaf.

Fixed by https://github.com/tapioca24/p5.capture/pull/7. Released in 1.2.0.
Could you please try it? Let me know if you have any problems.

**Comment by SableRaf** [comment]
Hi @tapioca24 :) I need to do more research with large sketches but my first quick test worked. I'll submit another issue if I find something. Thanks for your quick response!
