### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by werls** [tapioca24/p5.capture#8]
Thank you very much for this tool! I've been looking for an alternative to CCapture.js for some time now and this tool is perfect in every way: easy to use, flexible and easily adaptable to different sketches.

Unfortunately, I'm not getting a good result regarding the quality of the videos (mp4 and webm). I did some tests varying the quality between 0.1, 0.5 and 1.0 and the results are pretty much the same. The tests can be accessed [by this link](https://werls.xyz/temp/p5-capture-tests/).

Here's some screenshots of the tests:

---
Quality: 0.1
![Quality: 0.1](https://werls.xyz/temp/p5-capture-tests/quality-0point1.png)

---
*Quality: 0.5*
![Quality: 0.5](https://werls.xyz/temp/p5-capture-tests/quality-0point5.png)

---
*Quality: 1.0*
![Quality: 1.0](https://werls.xyz/temp/p5-capture-tests/quality-1.png)

---

I'm setting the options right on the code, before setup:
```
P5Capture.setDefaultOptions({  
  format: "mp4",  
  framerate: 60,  
  quality: 1.0,  
  width: 1080,  
});
```

Am I doing something wrong or is this behavior exactly what is expected?

**Comment by tapioca24** [comment]
Hi, @werls. Thank you for reporting this one!

`quality` option is only available for webm, gif, jpg, and webp.
You can use the `bitrate` option to control mp4 video quality.

**Comment by werls** [comment]
Thank you for the explanation. I will do some more tests and if I detect any problems I will forward it here.

**Comment by tapioca24** [comment]
There seems to be no problem so I am closing this.
If you have any problems, please create a new issue.

thanks
